# Generated by Django 3.1.2 on 2020-11-23 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('python_web_exam', '0002_auto_20201123_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
