# Generated by Django 3.1.3 on 2020-12-06 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_web_exam', '0004_auto_20201206_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
